package fr.le_campus_numerique.java.dd.game;

public enum GameStatus {
    IN_FIGHT, HERO_RETREAT, HERO_DEAD, ENNEMY_DEAD, PHILTER_ACTIVED, WEAPON_ACTIVED, SHIELD_ACTIVED, SPELL_ACTIVED, HERO_HEALS, POTION_STOCKED, EMPTY_SPACE, NOTHING_CHANGED;
}
